VBoxManage startvm awx.example.com --type headless
VBoxManage startvm gitlab.example.com --type headless
VBoxManage startvm artifactory.example.com --type headless
VBoxManage startvm jenkins.example.com --type headless
VBoxManage startvm dns.example.com --type headless
VBoxManage startvm prometheus.example.com --type headless
VBoxManage startvm grafana.example.com --type headless
VBoxManage startvm esmaster.example.com --type headless
VBoxManage startvm esdata1.example.com --type headless
VBoxManage startvm esdata2.example.com --type headless
VBoxManage startvm kibana.example.com --type headless
VBoxManage startvm logstash.example.com --type headless
VBoxManage startvm mysqldb.example.com --type headless
VBoxManage startvm mongodb.example.com --type headless
VBoxManage startvm controller.example.com --type headless
VBoxManage startvm hub.example.com --type headless
VBoxManage startvm eda.example.com --type headless
VBoxManage startvm gitlabrunner.example.com --type headless
VBoxManage startvm postgresdb.example.com --type headless
VBoxManage startvm jagent1.example.com --type headless
VBoxManage startvm vault.example.com --type headless
VBoxManage startvm ocmaster.example.com --type headless
VBoxManage startvm ocworker1.example.com --type headless
VBoxManage startvm ocworker2.example.com --type headless
VBoxManage startvm secopstools.example.com --type headless
