VBoxManage controlvm awx.example.com poweroff
VBoxManage controlvm gitlab.example.com poweroff
VBoxManage controlvm artifactory.example.com poweroff
VBoxManage controlvm jenkins.example.com poweroff
VBoxManage controlvm dns.example.com poweroff
VBoxManage controlvm prometheus.example.com poweroff
VBoxManage controlvm grafana.example.com poweroff
VBoxManage controlvm esmaster.example.com poweroff
VBoxManage controlvm esdata1.example.com poweroff
VBoxManage controlvm esdata2.example.com poweroff
VBoxManage controlvm kibana.example.com poweroff
VBoxManage controlvm logstash.example.com poweroff
VBoxManage controlvm mysqldb.example.com poweroff
VBoxManage controlvm mongodb.example.com poweroff
VBoxManage controlvm controller.example.com poweroff
VBoxManage controlvm hub.example.com poweroff
VBoxManage controlvm eda.example.com poweroff
VBoxManage controlvm gitlabrunner.example.com poweroff
VBoxManage controlvm postgresdb.example.com poweroff
VBoxManage controlvm jagent1.example.com poweroff
VBoxManage controlvm vault.example.com poweroff
VBoxManage controlvm ocmaster.example.com poweroff
VBoxManage controlvm ocworker1.example.com poweroff
VBoxManage controlvm ocworker2.example.com poweroff
VBoxManage controlvm secopstools.example.com poweroff
